name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 22.x
        cache: npm

    - name: Install dependencies
      run: npm ci

    - uses: reviewdog/action-setup@e04ffabe3898a0af8d0fb1af00c188831c4b5893 # v1.3.2
      with:
        reviewdog_version: latest # Optional. [latest,nightly,v.X.Y.Z]

    - name: lint
      id: lint
      run: |
        npx eslint . --ext .ts -f rdjson -o eslint-report.json || true
        cat eslint-report.json
        echo "lint_exit_code=$?" >> "$GITHUB_OUTPUT"

    - name: Publish lint results
      id: reviewdog
      run: |
        reviewdog -f=rdjson -reporter=github-check -name="ESLint" -fail-level=any < eslint-report.json
        echo "reviewdog_exit_code=$?" >> "$GITHUB_OUTPUT"

#    - name: ESLint and report to PR
#      id: reviewdog
#      uses: reviewdog/action-eslint@v1.33.2
#      with:
#        github_token: ${{ secrets.GITHUB_TOKEN }}
#        reporter: github-check
#        eslint_flags: 'src/**/*.ts'
#        filter_mode: file
#        fail_level: any

    - name: Capture lint exit code
      id: lint-capture
      run: echo "exit_code=${{ steps.reviewdog.outcome == 'success' && 0 || 1 }}" >> "$GITHUB_OUTPUT"

    - name: Run tests with coverage
      id: tests
      run: |
        npm run test:coverage
        echo "test_exit_code=$?" >> "$GITHUB_OUTPUT"

    - name: Fail if lint or tests failed
      run: |
        if [ "${{ steps.lint-capture.outputs.exit_code }}" != "0" ] || [ "${{ steps.tests.outputs.exit_code }}" != "0" ]; then
          echo "❌ Lint or tests failed"
          exit 1
        else
          echo "✅ Lint and tests passed"
        fi

    - name: Upload coverage reports
      uses: codecov/codecov-action@v4
      with:
        file: ./coverage/lcov.info
        fail_ci_if_error: false
